use work;
-- 1º
CREATE TABLE TB_CONTATO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_TELEFONE VARCHAR(20),
NM_EMAIL VARCHAR(70)
);

-- 2º
CREATE TABLE TB_IMPOSTO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
VL_AGUA DECIMAL(8,2),
VL_LUZ DECIMAL(8,2),
VL_ALUGUEL DECIMAL(8,2)
);

-- 3º
CREATE TABLE TB_SERVICOS(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_GUINCHO VARCHAR(30),
NM_COLISOES VARCHAR(30),
NM_ROUBO VARCHAR(30),
NM_ALAGAMENTO VARCHAR(30)
);

-- 4º
CREATE TABLE TB_COLABORADOR(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CD_CODIGO INT,
NM_NOME VARCHAR(100),
CD_CPF VARCHAR(14),
DT_NASCIMENTO DATE,
NM_CIDADE VARCHAR(200),
NM_UF VARCHAR(10),
NM_NUMERO VARCHAR(10)
);

-- 5º
CREATE TABLE TB_ALMOXARIFADO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CD_QUANTIDADE INT,
DT_COMPRA DATE,
DT_VENDA DATE
);

-- 6º
CREATE TABLE TB_REPOSICAO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_MODELO VARCHAR(45),
DS_OBSERVACAO  VARCHAR(200),
ID_TB_ALMOXARIFADO INT,
CONSTRAINT `FK_TB_ALMOXARIFADO` FOREIGN KEY (ID_TB_ALMOXARIFADO) REFERENCES TB_ALMOXARIFADO(ID)
);

-- 7º
CREATE TABLE TB_VISTORIA(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_AR VARCHAR(30),
NM_PNEUS VARCHAR(30),
NM_COMBUSTIVEL VARCHAR(30),
NM_QUILOMETRAGEM VARCHAR(30)
);

-- 8º
CREATE TABLE TB_WASHCAR(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_LAVAGEM VARCHAR(30),
NM_SECAGEM VARCHAR(30),
NM_POLIMENTO VARCHAR(30),
NM_CERA VARCHAR(30)
);

-- 9º
CREATE TABLE TB_CARGO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_TB_VISTORIA INT, 
ID_TB_WASHCAR INT,
CONSTRAINT `FK_TB_CARGO` FOREIGN KEY (ID_TB_VISTORIA) REFERENCES TB_VISTORIA(ID),
CONSTRAINT `FK_TB_CARGO_2` FOREIGN KEY (ID_TB_WASHCAR) REFERENCES TB_WASHCAR(ID)
);

-- 10º
CREATE TABLE TB_GERENCIA(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_TIPO_TREINAMENTO VARCHAR(45),
NM_METAS VARCHAR(45),
ID_TB_CARGO INT,
CONSTRAINT `FK_TB_GERENCIA` FOREIGN KEY (ID_TB_CARGO) REFERENCES TB_CARGO(ID)
);

-- 11º
CREATE TABLE TB_SEGURADORA(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_EMPRESA VARCHAR(45),
NM_DOCUMENTACAO VARCHAR(45),
NM_COBERTURA VARCHAR(45),
DT_TEMPO_DE_CONTRATO_DIAS INT,
ID_TB_SERVICOS INT,
CONSTRAINT `FK_TB_SEVICOS` FOREIGN KEY (ID_TB_SERVICOS) REFERENCES TB_SERVICOS(ID)
);

-- 12º
CREATE TABLE TB_CLIENTE(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_NOME VARCHAR(100),
CD_CPF VARCHAR(14),
DT_NASCIMENTO DATE,
NM_CIDADE VARCHAR(200),
NM_UF VARCHAR(10),
NM_NUMERO VARCHAR(10),
ID_TB_CONTATO INT,
CONSTRAINT `FK_TB_CLIENTE` FOREIGN KEY (ID_TB_CONTATO) REFERENCES TB_CONTATO(ID)
); 

-- 13º
CREATE TABLE TB_VENDA(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DS_OBSERVACAO VARCHAR(300),
VL_TOTAL DECIMAL(8,2),
CD_CODIGO INT,
DT_DATA DATETIME,
ID_TB_CLIENTE INT,
CONSTRAINT `FK_TB_VENDA` FOREIGN KEY (ID_TB_CLIENTE) REFERENCES TB_CLIENTE(ID)
);

-- 14º
CREATE TABLE TB_FINANCEIRO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DS_OBSERVACOES VARCHAR(200),
VL_GASTOS DECIMAL(8,2),
VL_GANHO DECIMAL(8,2),
VL_LUCRO DECIMAL(8,2),
ID_TB_VENDA INT,
ID_TB_SEGURADORA INT,
ID_TB_IMPOSTO INT,
CONSTRAINT `FK_TB_FINANCEIRO` FOREIGN KEY (ID_TB_VENDA) REFERENCES TB_VENDA(ID),
CONSTRAINT `FK_TB_FINANCEIRO_2` FOREIGN KEY (ID_TB_SEGURADORA) REFERENCES TB_SEGURADORA(ID),
CONSTRAINT `FK_TB_FINANCEIRO_3` FOREIGN KEY (ID_TB_IMPOSTO) REFERENCES TB_IMPOSTO(ID)
);

-- 15º
CREATE TABLE TB_CATALOGO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_MODELO VARCHAR(40),
NM_GARANTIA VARCHAR(45),
NM_CONTRATO VARCHAR(15),
ID_TB_FINANCEIRO INT,
CONSTRAINT `FK_TB_CATALOGO`FOREIGN KEY (ID_TB_FINANCEIRO) REFERENCES TB_FINANCEIRO(ID)
);

-- 16º
CREATE TABLE TB_SUPORTE(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_PROBLEMA VARCHAR(200),
ID_TB_VENDA INT,
CONSTRAINT `FK_TB_SUPORTE` FOREIGN KEY (ID_TB_VENDA) REFERENCES TB_VENDA(ID)
);

-- 17º
CREATE TABLE TB_CARRO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NM_QUILOMETRAGEM VARCHAR(15),
NM_LOCAIS VARCHAR(45),
NM_COR VARCHAR(30),
CD_ANO_FABRICACAO INT,
VL_PRECO DECIMAL(8,2),
ID_TB_CATALOGO INT,
CONSTRAINT `FK_TB_CARRO` FOREIGN KEY (ID_TB_CATALOGO) REFERENCES TB_CATALOGO(ID)
);

-- 18º
CREATE TABLE TB_COLABORADOR_CARRO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_TB_CARRO INT,
ID_TB_COLABORADOR INT,
CONSTRAINT `FK_TB_COLABORADOR_CARRO` FOREIGN KEY (ID_TB_CARRO) REFERENCES TB_CARRO(ID),
CONSTRAINT `FK_TB_COLABORADOR_CARRO_2` FOREIGN KEY (ID_TB_COLABORADOR) REFERENCES TB_COLABORADOR(ID)
);
