use work;
-- 1º VIEW
CREATE VIEW CATALOGO_CARRO as
SELECT c.NM_MODELO,c.NM_GARANTIA,cr.NM_QUILOMETRAGEM,cr.NM_COR,cr.VL_PRECO
FROM tb_catalogo c INNER JOIN
TB_CARRO cr ON
c.ID=cr.ID_TB_CATALOGO;

-- 2º VIEW
CREATE VIEW GERENCIA_CARGO as
SELECT g.NM_TIPO_TREINAMENTO,g.NM_METAS,c.ID_TB_VISTORIA as TRABALHADOR_VISTORIA,c.ID_TB_WASHCAR as TRABALHADOR_WASHCAR
FROM TB_GERENCIA g INNER JOIN
TB_CARGO c ON
g.ID=c.ID_TB_VISTORIA;

-- 3º VIEW
CREATE VIEW ALMOXARIFADO_REPOSICAO as
SELECT r.NM_MODELO,a.CD_QUANTIDADE,a.DT_COMPRA,a.DT_VENDA
FROM TB_ALMOXARIFADO a INNER JOIN
TB_REPOSICAO r ON
a.ID=r.ID_TB_ALMOXARIFADO;

-- 4º VIEW
CREATE VIEW CONTATO_CLIENTE as
SELECT cl.NM_NOME,cl.CD_CPF,c.NM_TELEFONE,c.NM_EMAIL,cl.DT_NASCIMENTO,cl.NM_CIDADE
FROM TB_CONTATO c INNER JOIN
TB_CLIENTE cl ON
c.ID=cl.ID_TB_CONTATO;

-- 5º VIEW
CREATE VIEW VENDA_FINANCEIRO as
SELECT f.VL_GASTOS,f.VL_GANHO, f.VL_LUCRO, count(CD_CODIGO) as QUANTIDADE_VENDA
FROM TB_VENDA v INNER JOIN
TB_FINANCEIRO f ON
v.ID=f.ID_TB_SEGURADORA;

-- 6º VIEW
CREATE VIEW SERVICOS_SEGURADORA as
SELECT s.NM_EMPRESA,s.NM_COBERTURA,s.DT_TEMPO_DE_CONTRATO_DIAS,sv.NM_GUINCHO,sv.NM_COLISOES,sv.NM_ROUBO,sv.NM_ALAGAMENTO
FROM TB_SERVICOS sv INNER JOIN
TB_SEGURADORA s ON
sv.ID=s.ID_TB_SERVICOS;

-- 7º VIEW
CREATE VIEW CLIENTE_VENDA as
SELECT C.NM_NOME,C.CD_CPF,V.VL_TOTAL as VALOR_GASTO,V.DT_DATA
FROM TB_CLIENTE c INNER JOIN
TB_VENDA v ON
c.ID=v.ID_TB_CLIENTE;

-- 8º VIEW
CREATE VIEW VENDA_SUPORTE as
SELECT V.CD_CODIGO as CODIGO_VENDA,V.DT_DATA as DATA_VENDA,S.NM_PROBLEMA
FROM TB_VENDA v INNER JOIN
TB_SUPORTE s ON
v.ID=s.ID_TB_VENDA;
